#!/bin/bash
# ATLAS 网站截图指南

echo "🖼️  ATLAS 网站截图指南"
echo "================================"
echo ""
echo "方法 1: Chrome 开发者工具（推荐）"
echo "1. 打开网站页面"
echo "2. 按 Cmd + Option + I 打开开发者工具"
echo "3. 按 Cmd + Shift + P"
echo "4. 输入 'screenshot'"
echo "5. 选择 'Capture full size screenshot'"
echo ""
echo "方法 2: macOS 自带截图"
echo "1. 按 Cmd + Shift + 5"
echo "2. 选择截图区域"
echo "3. 点击拍摄"
echo ""
echo "📝 需要截图的页面清单："
echo "================================"
echo ""
echo "核心页面（必须）："
echo "  ✓ index.html - 首页落地页"
echo "  ✓ home.html - 工作台"
echo "  ✓ ask.html - AI 助手"
echo "  ✓ memory.html - 记忆管理"
echo "  ✓ life.html - 生活管理"
echo "  ✓ agents.html - 智能体"
echo "  ✓ settings.html - 设置"
echo ""
echo "子页面（选择性）："
echo "  ✓ memory-personal.html - 个人信息"
echo "  ✓ life-calendar.html - 日历"
echo "  ✓ life-tasks.html - 任务管理"
echo "  ✓ agents-travel.html - 旅行规划"
echo "  ✓ settings-appearance.html - 外观设置"
echo ""
echo "💡 截图建议："
echo "  • 分辨率：1920x1080 或更高"
echo "  • 格式：PNG（更清晰）"
echo "  • 命名：01-index.png, 02-home.png..."
echo "  • 存储位置：创建 screenshots/ 文件夹"
echo ""
echo "📂 创建截图文件夹..."
mkdir -p screenshots
echo "✅ 文件夹已创建：screenshots/"
echo ""
echo "现在请打开浏览器开始截图！"
